// user
export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_SET_TOKEN = "USER_SET_TOKEN";
export const USER_LOGOUT = "USER_LOGOUT";
export const RESET_ERROR = "RESET_ERROR";

//jobs
export const JOBS_FETCH_BEGIN = "JOBS_FETCH_BEGIN";
export const JOBS_FETCH_SUCCESS = "JOBS_FETCH_SUCCESS";
export const JOBS_FETCH_FAILURE = "JOBS_FETCH_FAILURE";
